spring:
    application:
        name: Internet Shop

    sql:
        init:
            mode: always

    r2dbc:
        url: ${INTERSHOP_DB_URL}
        username: ${INTERSHOP_DB_USERNAME}
        password: ${INTERSHOP_DB_PASSWORD}

        pool:
            max-size: 20
            initial-size: 10
            validation-query: SELECT 1 # Проверка доступности соединения

    data:
        redis:
            host: ${REDIS_HOST}
            port: 6379
            cache:
                redis:
                    time-to-live: PT5S    # TTL по умолчанию для кешей

upload.images.dir: ${UPLOAD_IMAGES_DIR:/app/images}

cookie:
    max:
        age:
            seconds: 86400
    logging:
        level:
    #        org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG # заодно включим логирование SQL-запросов
    #    io.r2dbc: DEBUG # и добавим больше деталей (не включать в настоящем приложении)
            org.springframework.data.redis: DEBUG

balance:
    service:
        url:  http://${PAYMENT_SERVICE_HOST}:8081

