spring:
    application:
        name: Internet Shop

    datasource:
        driver-class-name: org.postgresql.Driver

        url: ${INTERSHOP_DB_URL}
        username: ${INTERSHOP_DB_USERNAME}
        password: ${INTERSHOP_DB_PASSWORD}

    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml

upload.images.dir: C:/Users/79185/IdeaProjects/YandexPracticum Projects/sprint-5/intershop/src/main/webapp/images
cookie.max.age.seconds: 86400  # 1 day in seconds (60 × 60 × 24)

---
spring:
    config:
        activate:
            on-profile: test

    datasource:
        url: ${INTERSHOP_TEST_DB_URL}
        username: ${INTERSHOP_DB_USERNAME}
        password: ${INTERSHOP_DB_PASSWORD}

    liquibase:
        contexts: 'test'