spring:
    application:
        name: Internet Shop

    r2dbc:
        url: r2dbc:postgresql://localhost:5432/intershop-db # INTERSHOP_DB_URL = localhost:5432/your_database_name
        username: postgres
        password: postgres

    flyway:
        locations: classpath:/db/migration  # Путь к вашим SQL-скриптам Flyway
        enabled: true  # Включить Flyway
        baseline-on-migrate: true # Создать baseline таблицу если её нет при миграции

upload.images.dir: ${UPLOAD_IMAGES_DIR:/app/images}

cookie:
    user:
        id:
            name: userId

    max:
        age:
            seconds: 86400


