server:
  port: 8081

spring:
  application:
    name: Internet Shop

  sql:
    init:
      mode: always

  r2dbc:
    url: ${PAYMENT_SERVICE_DB_URL}
    username: ${PAYMENT_SERVICE_DB_USERNAME}
    password: ${PAYMENT_SERVICE_DB_PASSWORD}

    pool:
      max-size: 20
      initial-size: 10
      validation-query: SELECT 1 # Проверка доступности соединения

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOACK_ISSUER_HOST_AND_PORT:localhost:8082}/realms/master